# @Author: michael
# @Date:   24-Sep-2018
# @Filename: .gitlab-ci.yml
# @Last modified by:   michael
# @Last modified time: 26-Jun-2019
# @License: GNU GPL v3

stages:
    - build
    - test
    - deploy

test:
    stage: test
    script:
      - apt-get update -qq && apt-get install -y python3-pip python3 net-tools graphviz traceroute
      - pip3 install -r requirements.txt
      - cp ./test/install/config.test ./config.py
      - fab install
      - fab test


code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]
