# @Author: michael
# @Date:   24-Sep-2018
# @Filename: .gitlab-ci.yml
# @Last modified by:   michael
# @Last modified time: 26-Jun-2019
# @License: GNU GPL v3

include:
  - template: Code-Quality.gitlab-ci.yml


stages:
    - build
    - test
    - deploy

test:
    stage: test
    script:
      - apt-get update -qq && apt-get install -y python3-pip python3 net-tools graphviz traceroute
      - pip3 install -r requirements.txt
      - cp ./test/install/config.test ./config.py
      - fab install
      - fab prepare-data-test
      - python3 -m pytest

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]
