# @Author: michael
# @Date:   24-Sep-2018
# @Filename: .gitlab-ci.yml
# @Last modified by:   michael
# @Last modified time: 26-Jun-2019
# @License: GNU GPL v3


stages:
  - test
  - test-code

before_script:
  - apt-get update -qq && apt-get install -y python3-pip python3 net-tools graphviz traceroute
  - pip3 install poetry
  - poetry install
  - cp ./test/install/config.test ./config.py
  - poetry run invoke install
  - poetry run invoke prepare-data-test


test:
  stage: test
  script:
    - poetry run invoke test


test-code:
  stage: test-code
  script:
    - poetry run invoke test-code
